// WARNING: this file was generated automatically by balde-template-gen

#include <balde.h>
#include <glib.h>

extern gchar* balde_str_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response);
extern void balde_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response);

gchar*
balde_str_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    GString *rv = g_string_new("");
    g_string_append(rv, "<html>\n<head><title>");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "title"));
    g_string_append(rv, "</title></head>\n<body>\n<h1>");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "title"));
    g_string_append(rv, "</h1>\n");
    if (balde_response_get_tmpl_var(response, "name") != NULL) {
        g_string_append(rv, "\nName: ");
        g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "name"));
        g_string_append(rv, "\n");
        if (balde_response_get_tmpl_var(response, "surname") != NULL) {
            g_string_append(rv, "\nSurname: ");
            g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "surname"));
            g_string_append(rv, "\n");
        }
        else {
            g_string_append(rv, "\nNo surname!\n");
        }
        g_string_append(rv, "\n");
    }
    g_string_append(rv, "\n</body>\n</html>\n");
    return g_string_free(rv, FALSE);
}

void
balde_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    gchar *rv = balde_str_template_bola(app, request, response);
    balde_response_append_body(response, rv);
    g_free(rv);
}
