// WARNING: this file was generated automatically by balde-template-gen

#include <balde.h>
#include <glib.h>

extern gchar* balde_str_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response);
extern void balde_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response);

gchar*
balde_str_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    GString *rv = g_string_new("");
    g_string_append(rv, "<html>\n<head><title>");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "title"));
    g_string_append(rv, "</title></head>\n<body>\n<h1>");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "title"));
    g_string_append(rv, "</h1>\n");
    g_string_append(rv, "<h2>");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "subtitle"));
    g_string_append(rv, "</h2>\n<p>This page is: ");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "name"));
    g_string_append(rv, "</p>\n");
    g_string_append(rv, "\n</body>\n</html>\n");
    return g_string_free(rv, FALSE);
}

void
balde_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    gchar *rv = balde_str_template_bola(app, request, response);
    balde_response_append_body(response, rv);
    g_free(rv);
}
