// WARNING: this file was generated automatically by balde-template-gen

#include <balde.h>
#include <glib.h>

extern gchar* balde_str_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response);
extern void balde_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response);

gchar*
balde_str_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    GString *rv = g_string_new("");
    gchar *tmp;
    g_string_append(rv, "ads ");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "guda"));
    g_string_append(rv, "\n\n");
    tmp = balde_tmpl_bola(app, request);
    g_string_append(rv, tmp);
    g_free(tmp);
    g_string_append(rv, "\n\n");
    tmp = balde_tmpl_chunda(app, request, balde_response_get_tmpl_var(response, "quico"), "cola", -2, 1.5, "chaves", TRUE, balde_response_get_tmpl_var(response, "popis"), "bo'la");
    g_string_append(rv, tmp);
    g_free(tmp);
    g_string_append(rv, " ");
    tmp = balde_tmpl_asd(app, request, "XD");
    g_string_append(rv, tmp);
    g_free(tmp);
    g_string_append(rv, "\n");
    g_string_append(rv, balde_response_get_tmpl_var_or_empty(response, "balde"));
    g_string_append(rv, " qwe\n");
    return g_string_free(rv, FALSE);
}

void
balde_template_bola(balde_app_t *app, balde_request_t *request, balde_response_t *response)
{
    gchar *rv = balde_str_template_bola(app, request, response);
    balde_response_append_body(response, rv);
    g_free(rv);
}
