BUNDLE_VERSION=0.3

GLOBAL_PREFIX="${SEMAPHORE_CACHE_DIR}/prefix"
APT_CACHE="${SEMAPHORE_CACHE_DIR}/apt"

GLIB_PREFIX="${GLOBAL_PREFIX}/glib"
GLIB_BUILD="/tmp/glib-build"
GLIB_VERSIONS=( 2.35.9 2.40.2 2.44.0 )
