/*
 * balde: A microframework for C based on GLib and bad intentions.
 * Copyright (C) 2013-2015 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 *
 * This program can be distributed under the terms of the LGPL-2 License.
 * See the file COPYING.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif /* HAVE_CONFIG_H */

#include <glib.h>
#include "config.h"
#include "static.h"
#include "template.h"
#include "theme.h"


GString*
balde_theme_generate_source(const gchar *sourcedir, balde_theme_config_t *config)
{
    GString *rv = g_string_new(
        "// WARNING: this file was generated automatically by balde-theme-gen\n"
        "\n"
        "#include <balde.h>\n"
        "#include <glib.h>\n");

    for (guint i = 0; config->includes[i] != NULL; i++)
        g_string_append_printf(rv, "#include <%s>\n", config->includes[i]);

    g_string_append(rv, "\n\n");

    GBytes *b = balde_theme_static_get_resource_data(sourcedir, config->static_resources);
    gchar *resources = balde_theme_static_render_resource_data(b);
    g_string_append_printf(rv,
        "static guint8 resources_data[%" G_GSIZE_FORMAT "] = %s;\n\n\n",
        g_bytes_get_size(b), resources);
    g_free(resources);
    g_bytes_unref(b);

    for (guint i = 0; config->templates[i] != NULL; i++) {
        gchar *filename = g_build_filename(sourcedir, config->templates[i], NULL);
        gchar *function = g_strdup_printf("template_callback_%d", i);
        balde_template_state_t *state = NULL;
        balde_template_build_state(filename, &state);
        g_string_append(rv, "static ");
        balde_template_generate_str_function(function, rv, state);
        g_string_append(rv, "\n\n");
        g_free(function);
        g_free(filename);
    }

    g_string_append(rv,
        "static balde_theme_t*\n"
        "get_theme(void)\n"
        "{\n"
        "    balde_theme_t *theme = balde_theme_new(resources_data, sizeof(resources_data));\n");

    for (guint i = 0; config->templates[i] != NULL; i++)
        g_string_append_printf(rv,
            "    balde_theme_add_template(theme, \"%s\", template_callback_%d);\n",
            config->templates[i], i);

    g_string_append(rv,
        "    return theme;\n"
        "}\n\n\n");

    g_print("%s\n", rv->str);

    return rv;
}
